### ISSUE TITLE
which version you use in this project?

### ISSUE THREAD

**Issue by flyingbird93** [subpic/ava-mlsp#1]
hi, I see your study in aesthetic assessment, it`s so exciting to improve the SROCC and LCC to 0.75.
I want to know which version you use keras and tensorflow, could your please write a requirements
for us to apply your results quickly.

**Comment by subpic** [comment]
Hi,

The environment I'm running the code under is:
```
Python 2.7.16 :: Anaconda, Inc 
tensorflow-gpu 1.14.0
keras-gpu 2.2.4
```

The code runs on google colab as well, see [notebook example here](http://bit.ly/2lPTWyH). The training itself is slower on colab due to slower disk reads, than when using your own SSD.

Alternatively you can deploy the code via docker using the Python 2 environment in [jupyter-data-science](https://github.com/subpic/jupyter-data-science).

Best,
Vlad
